services:
  postgres-eventos:
    image: postgres:16
    container_name: eventpass-eventos-db
    environment:
      POSTGRES_DB: eventos_db
      POSTGRES_USER: eventpass
      POSTGRES_PASSWORD: eventpass
    ports:
      - "5434:5432"
    volumes:
      - eventos_data:/var/lib/postgresql/data

volumes:
  eventos_data:
